### ISSUE TITLE
CCnet training on ADE20K

### ISSUE THREAD

**Issue by shengtao96** [speedinghzl/CCNet#18]
I try to training the CCnet on the ADE20K dataset. Unfortunately, I get a bad result.
Could you release your training code on the ADE20K ?

**Comment by speedinghzl** [comment]
I run CCNet on ADE20K with the modified [semantic-segmentation-pytorch](https://github.com/CSAILVision/semantic-segmentation-pytorch). Maybe you can try to build CCNet on it.
I will reorganize the code of my another repo [pytorch-segmentation-toolbox](https://github.com/speedinghzl/pytorch-segmentation-toolbox) to support CCNet( and other models) and ADE20K(other datasets) in March or April.
