### ISSUE TITLE
About road segmentation

### ISSUE THREAD

**Issue by Amore-HDU** [speedinghzl/CCNet#20]
Hello，
Now I try to use CCNet to segment Road.
In my mask images, road is set 255 while others are set 0.
NUM_CLASSES=2, self.id_to_trainid={0:0, 255:255}.
It quickly convergence.But when I run test.py,the output image is all black.
I want  to knows what's wrong?
Thx @speedinghzl

**Comment by speedinghzl** [comment]
255 is used as ignore label. You can use this mapping {0:0, your_road_id:1, ignore_id:255}
