### ISSUE TITLE
Ask for resources of CUDAImplementation

### ISSUE THREAD

**Issue by zhangfb** [speedinghzl/CCNet#21]
Hi, the idea of cross-criss attention is impressive and inspiring and the code released is very helpful to me.

 I am a starter in the DL area, and I want to further learn how to implement some computational codes in CUDA just like you implementing computational part of cross-criss attention in CUDA. So is there any resources in English or Chinese that you suggest to learn? 

Thank you in advance for helping me!

**Comment by speedinghzl** [comment]
Thank you for your interest in our work.
I learned basic knowledge about CUDA parallel programming via the [website](https://classroom.udacity.com/courses/cs344) and the book named [CUDA by Example](http://www.mat.unimi.it/users/sansotte/cuda/CUDA_by_Example.pdf). 
If you want to write more effective programs, maybe the [professional book](http://www.hds.bme.hu/~fhegedus/C++/Professional%20CUDA%20C%20Programming.pdf) is necessary to read and practice.

**Comment by zhangfb** [comment]
> Thanks for your interest in our work.
> I learned basic knowledge about CUDA parallel programming via the [website](https://classroom.udacity.com/courses/cs344) and the book named [CUDA by Example](http://www.mat.unimi.it/users/sansotte/cuda/CUDA_by_Example.pdf).
> If you want to write more effective programs, maybe the [professional book](http://www.hds.bme.hu/~fhegedus/C++/Professional%20CUDA%20C%20Programming.pdf) is necessary to read and practice.

Thank you so much!
