### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by dontLoveBugs** [speedinghzl/CCNet#23]
When I compiled the "cc_atttenion", I get the error "cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1". My environment is Ubuntu 16.04, CUDA 8.0, python3.6 with pytorch 0.4.1. Could you help me?
![image](https://user-images.githubusercontent.com/17598076/53613312-ae203380-3c10-11e9-9db4-3e31de46de93.png)

**Comment by CZ-Wu** [comment]
> When I compiled the "cc_atttenion", I get the error "cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1". My environment is Ubuntu 16.04, CUDA 8.0, python3.6 with pytorch 0.4.1. Could you help me?

I modify line 20 in lib/build.py to `extra_compile_args=["-std=c++11"]`. It works.
