### ISSUE TITLE
How can I split the picture into two parts?

### ISSUE THREAD

**Issue by wmj1238** [speedinghzl/CCNet#35]
Dear author,
thank you for your excellent work. I have a question. If I want to split only the specific scenes in the image, how do I change the code? For example, I just want to split the car in the picture.Should I modify the“--num-classes” ？

**Comment by speedinghzl** [comment]
There are two alternative solutions. 1. Without training, you can still use the [trained model](https://github.com/speedinghzl/CCNet#models) to parse an image into a 19-category map, then convert the predicted 19-category map into a 2-category map. 2. Need to train the mode again. First of all, add the parameters --num-classes 2 in the scripts. Then, modify the index mapping function in [dataset.py](https://github.com/speedinghzl/CCNet/blob/master/dataset/datasets.py#L146)(map the index of the car into 1, and map the others into 0). Finally, start to train the model.

**Comment by wmj1238** [comment]
Thanks for your help, I understand what to do next.
