### ISSUE TITLE
The different reported performances between table 1 and table 4.

### ISSUE THREAD

**Issue by tanxin2017** [speedinghzl/CCNet#47]
Hi, Thanks for you work.
I am curious that why the preformance of CCNET on table 1 is 81.3 while that on table 4 is 79.8. It seems they are under the same setting and should be the same network. Do I miss some details?

Thanks!

**Comment by speedinghzl** [comment]
In Table 1, we use multi-scale and horizontal flip strategies for inference. 
In Table 4, we do not take these strategies.

**Comment by tanxin2017** [comment]
Thanks!
