### ISSUE TITLE
Have you tried multiscale test?

### ISSUE THREAD

**Issue by Howal** [speedinghzl/CCNet#50]
I have tried multiscale-test of the master branch.
There seems no improvment of performance.
For branch-pytorch1.1, it seems bug remains (prob shape mismatch), if replace [1.0] with [0.75, 1.0, 1.25] directly.

**Comment by speedinghzl** [comment]
Yes, I have.

**Comment by cauivy** [comment]
> , it seems bug remains (prob shape mismatch), if replace [1.0] with [0.75, 1.0, 1.25] directly.

Got the same bug when trying multiscale test...
