### ISSUE TITLE
Do you have any suggestions if I try to use RCCA module in my own segmentation network?

### ISSUE THREAD

**Issue by ginobilinie** [speedinghzl/CCNet#52]
Thanks for your great work. I have tried to use the RCCA module you developed in my own segmentation network, in particular, I place this module in the end of segmentation network. However, it cannot improve the performance. Can you please give some suggestions for using the RCCA module?

Thanks.

**Comment by speedinghzl** [comment]
have replied in the email.

**Comment by llldream001** [comment]
Can you send the suggestions to me  ? I've tried the RCCA module in my segmentation network ,but got no improvement .Thank you! @speedinghzl
