### ISSUE TITLE
The formula for criss-cross Attention

### ISSUE THREAD

**Issue by Amorzhang** [speedinghzl/CCNet#55]
![image](https://user-images.githubusercontent.com/14356642/69840755-9d801500-1297-11ea-807d-02eb5ff8420c.png)
    I recently read your paper and have some questions about the formula. What does the ∑ above mean? How does it work？ 
![image](https://user-images.githubusercontent.com/14356642/69840814-e33cdd80-1297-11ea-955e-d2d3e3ed4ad2.png)
![image](https://user-images.githubusercontent.com/14356642/69840826-ed5edc00-1297-11ea-98b9-89f9d7877bf4.png)
I found that the number of channels between them was not the same, while the number of channels to H‘ was C.

**Comment by speedinghzl** [comment]
A_{i,u} is a scalar.
![image](https://user-images.githubusercontent.com/4509744/70843777-f8f2fb00-1e72-11ea-9558-9f915f2081f7.png)

**Comment by Amorzhang** [comment]
Thanks
