### ISSUE TITLE
nvcc: not found

### ISSUE THREAD

**Issue by TianMingChen** [speedinghzl/CCNet#56]
build.sh: 11: build.sh: nvcc: not found
![image](https://user-images.githubusercontent.com/20785298/69956208-52d1f780-153a-11ea-8c6f-8e8b277a8e25.png)
hello，such problem hapeened,i have write the path in  ~/.bashrc ,do you have some solution?
export CUDA_HOME=/usr/local/cuda
export PATH=$PATH:/usr/local/cuda-9.0/bin
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

**Comment by TianMingChen** [comment]
![image](https://user-images.githubusercontent.com/20785298/69959590-831d9400-1542-11ea-8521-19ac0256d4f0.png)
it have nvcc install

**Comment by TianMingChen** [comment]
![image](https://user-images.githubusercontent.com/20785298/69959800-ec050c00-1542-11ea-8839-a4c6c43b39fc.png)

**Comment by TianMingChen** [comment]
![image](https://user-images.githubusercontent.com/20785298/69959848-0212cc80-1543-11ea-87bf-f2697be65aa6.png)

**Comment by speedinghzl** [comment]
I notice that you run the script with sudo. That's the problem.

**Comment by TianMingChen** [comment]
> I notice that you run the script with sudo. That's the problem.

Wow,Thank you !
