### ISSUE TITLE
the Influence about the gama??

### ISSUE THREAD

**Issue by zrl4836** [speedinghzl/CCNet#58]
https://github.com/speedinghzl/CCNet/blob/7a76bff58afe5cffab78af921cddda5f10caa611/cc_attention/functions.py#L90
Can you tell me abou it ? why do you use it?

**Comment by speedinghzl** [comment]
When inserting the RCCA module into the intermediate layer of CNNs, we don't want to break the structure (feature) learned from ImageNet at the beginning of training, so we can set gamma to zero.

**Comment by zrl4836** [comment]
OK，thank you
