### ISSUE TITLE
Different BN-Activation type 

### ISSUE THREAD

**Issue by EthanZhangYi** [speedinghzl/CCNet#6]
Some BNs are `InPlaceABNSync` with `activation='none'` (in backbone) and others are `InPlaceABNSync` with `activation='leaky_relu'` (in `head` and `dsn`).
Why?

**Comment by speedinghzl** [comment]
In Resnet-101 settings, all batchnorm are followed by ReLU. This is the reason why InPlaceABNSync with activation='none' followed by ReLU appear in backbone. We use InPlaceABNSync with activation='leaky_relu' in head and dsn to save memory. Please refer to [inplace_abn](https://arxiv.org/abs/1712.02616) for more details.

**Comment by EthanZhangYi** [comment]
@speedinghzl  Thanks for your reply.
(1) There is only one BN layer in `head` and `dsn`. I think only a little memory will be saved.
(2) According to the log file supplied in #4 , you use `activation='none'` in `dsn`, which dose NOT match this repo.

**Comment by speedinghzl** [comment]
@EthanZhangYi 
1）don't do nothing due to the benefit is little.
2)  we renew the code and release the corresponding trained model.

**Comment by EthanZhangYi** [comment]
@speedinghzl  Thanks for your reply.
