### ISSUE TITLE
about the detail of cc-attention mathematical derivation

### ISSUE THREAD

**Issue by pupil011** [speedinghzl/CCNet#86]
i dont know why size of  Ωu  = (H+W-1)×C‘
how to got it (H+W-1) ?
looking forward to your reply!

**Comment by speedinghzl** [comment]
@pupil011  For position u, the features of pixels in the same row or column with position u could form Ωu. There are **W** elements in the horizontal direction and **H** elements in the vertical direction. The position u is recorded twice. So the size of  Ωu = (H+W-1)×C‘.

**Comment by pupil011** [comment]
Thank you,i can clearly to understand .
it's a wonderful&nbsp; explanation!





---Original---
