### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by nooriahmed** [speedinghzl/CCNet#9]
Thanks for this grateful implementation. I am training cityscapes dataset. But I am facing this issue. seeking help. I will be very thankful. Regards
File "/adata/Naushad/CCNet/dataset/datasets.py", line 164, in id2trainId
    label_copy = label.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by speedinghzl** [comment]
@nooriahmed Please make sure your data loader can access the images and labels firstly.

**Comment by HqWei** [comment]
It should be that the path to the data is wrong.

**Comment by nooriahmed** [comment]
Great. please correct me if I am wrong "dataset.py" is for VOC dataset.  could you please provide cityscape dataset loader. I shall be very grateful to you...

**Comment by speedinghzl** [comment]
@nooriahmed Please go through the whole file "dataset.py", you will get data loader for cityscapes.
